file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
set(INPUT "${WORK}/program.qc")
file(WRITE "${INPUT}" "adder=fu(x){return fu(y){return x+y;};}; result=adder(1)(2); exact=36.6*1.2; return x+0; return 1/0; return false&&f(); return $.left.self.value; return @.list{0,1};")

execute_process(COMMAND "${QPILER}" "${INPUT}" RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR)
if(NOT RESULT EQUAL 0 OR NOT OUTPUT STREQUAL "" OR NOT ERROR STREQUAL "" OR EXISTS "${INPUT}.dump")
    message(FATAL_ERROR "normal compile contract failed: ${RESULT} ${OUTPUT} ${ERROR}")
endif()
execute_process(COMMAND "${QPILER}" --dump "${INPUT}" RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR)
if(NOT RESULT EQUAL 0 OR NOT OUTPUT STREQUAL "" OR NOT ERROR STREQUAL "")
    message(FATAL_ERROR "dump compile failed: ${RESULT} ${OUTPUT} ${ERROR}")
endif()
file(READ "${INPUT}.dump/00.tokens" TOKENS)
file(READ "${INPUT}.dump/01.normalized" AST)
file(READ "${INPUT}.dump/02.reduced" REDUCED)
file(READ "${INPUT}.dump/03.reduction" REASONS)
if(TOKENS STREQUAL "" OR NOT AST MATCHES "function" OR NOT AST MATCHES "call"
   OR NOT AST MATCHES "root" OR NOT AST MATCHES "current" OR NOT AST MATCHES "select"
   OR NOT REDUCED MATCHES "1098/25" OR NOT REASONS MATCHES "unknown_symbol"
   OR NOT REASONS MATCHES "division_by_zero" OR NOT REASONS MATCHES "known")
    message(FATAL_ERROR "missing compiler artifacts")
endif()
execute_process(COMMAND "${QPILER}" --dump "${INPUT}" RESULT_VARIABLE RESULT)
file(READ "${INPUT}.dump/00.tokens" AGAIN_TOKENS)
file(READ "${INPUT}.dump/01.normalized" AGAIN_AST)
file(READ "${INPUT}.dump/02.reduced" AGAIN_REDUCED)
file(READ "${INPUT}.dump/03.reduction" AGAIN_REASONS)
if(NOT RESULT EQUAL 0 OR NOT TOKENS STREQUAL AGAIN_TOKENS OR NOT AST STREQUAL AGAIN_AST
   OR NOT REDUCED STREQUAL AGAIN_REDUCED OR NOT REASONS STREQUAL AGAIN_REASONS)
    message(FATAL_ERROR "unstable compiler artifacts")
endif()
file(WRITE "${INPUT}.dump/01.normalized" "sentinel")
file(WRITE "${INPUT}.dump/02.reduced" "reduced sentinel")
file(WRITE "${INPUT}.dump/03.reduction" "reasons sentinel")
execute_process(COMMAND "${QPILER}" "${INPUT}" RESULT_VARIABLE RESULT)
file(READ "${INPUT}.dump/01.normalized" UNCHANGED)
file(READ "${INPUT}.dump/02.reduced" UNCHANGED_REDUCED)
file(READ "${INPUT}.dump/03.reduction" UNCHANGED_REASONS)
if(NOT RESULT EQUAL 0 OR NOT UNCHANGED STREQUAL "sentinel"
   OR NOT UNCHANGED_REDUCED STREQUAL "reduced sentinel" OR NOT UNCHANGED_REASONS STREQUAL "reasons sentinel")
    message(FATAL_ERROR "normal compile touched dump artifacts")
endif()
set(GROWTH "${WORK}/growth.qc")
file(WRITE "${GROWTH}" "return 1e999999999999999999999999;")
execute_process(COMMAND "${QPILER}" "${GROWTH}" RESULT_VARIABLE NORMAL_RESULT OUTPUT_VARIABLE NORMAL_OUTPUT ERROR_VARIABLE NORMAL_ERROR)
execute_process(COMMAND "${QPILER}" --dump "${GROWTH}" RESULT_VARIABLE DUMP_RESULT OUTPUT_VARIABLE DUMP_OUTPUT ERROR_VARIABLE DUMP_ERROR)
file(READ "${GROWTH}.dump/03.reduction" GROWTH_REASONS)
if(NOT NORMAL_RESULT EQUAL 0 OR NOT DUMP_RESULT EQUAL 0
   OR NOT NORMAL_OUTPUT STREQUAL DUMP_OUTPUT OR NOT NORMAL_ERROR STREQUAL DUMP_ERROR
   OR NOT GROWTH_REASONS MATCHES "numeric_growth")
    message(FATAL_ERROR "growth should remain residual in both modes")
endif()
set(BAD "${WORK}/bad.qc")
file(WRITE "${BAD}" "return a.;")
foreach(MODE IN ITEMS normal dump)
    if(MODE STREQUAL "dump")
        set(ARGS --dump)
    else()
        set(ARGS)
    endif()
    execute_process(COMMAND "${QPILER}" ${ARGS} "${BAD}" RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR)
    if(NOT RESULT EQUAL 1 OR NOT ERROR MATCHES "bad.qc:1:" OR EXISTS "${BAD}.dump")
        message(FATAL_ERROR "invalid-input contract failed: ${RESULT} ${OUTPUT} ${ERROR}")
    endif()
endforeach()
set(BLOCKED "${WORK}/blocked.qc")
file(WRITE "${BLOCKED}" "return 1;")
file(WRITE "${BLOCKED}.dump" "occupied")
execute_process(COMMAND "${QPILER}" --dump "${BLOCKED}" RESULT_VARIABLE RESULT ERROR_VARIABLE ERROR)
if(NOT RESULT EQUAL 1 OR ERROR STREQUAL "")
    message(FATAL_ERROR "dump I/O error was ignored")
endif()
execute_process(COMMAND "${QPILER}" --help RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT)
if(NOT RESULT EQUAL 0 OR NOT OUTPUT MATCHES "dump")
    message(FATAL_ERROR "help does not describe dump mode")
endif()
